name: terracode_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  intl: ^0.19.0
  pdf: ^3.10.4
  printing: ^5.11.0
  go_router: ^17.1.0
  google_fonts: ^8.0.0
  flutter_svg: ^2.2.3
  font_awesome_flutter: ^10.12.0
  google_maps_flutter: ^2.14.0
  fl_chart: ^1.1.1
  image_picker: ^1.0.7  
  firebase_storage: 13.0.6 
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: "^2.4.4"

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_screen.png.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/splash_screen.png.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#0A1128"
  image: "assets/images/splash_screen.png.png" 
  android: true
  ios: true
  fullscreen: true